name: "dbt_core_dataengineer"
version: "1.0.0"
config-version: 2

profile: "dbt_core_dataengineer"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_core_dataengineer:
    staging:
      +catalog: bronze
      +schema: staging
      +materialized: view

    silver:
      +catalog: silver
      +schema: silver
      +materialized: table

    gold:
      +catalog: gold
      +schema: gold
      +materialized: table